theme: jekyll-theme-minimal
title: PyKidsClub
logo: /images/PYKIDSCLUB.jpg
description: <pre> <a href="mailto:pykidsclub@gmail.com?Subject=Information on PyKidsClub" target="_top">Email Us</a>     ⋅     <a href="http://pykidsclub.com/enroll">Enroll</a>     ⋅     <a href="http://pykidsclub.com/about">About </a> </pre>
github:
  is_project_page: false
