theme: jekyll-theme-minimal
title: PyKidsClub
description: Welcome to PyKidsClub - A club for learning Python and STEM concepts for Middle School Students
logo: https://github.com/pykidsclub/index/blob/master/images/PYKIDSCLUB.jpg
